name = "federation-compatibility"
compatibility_date = "2024-04-03"
node_compat = true

[limits]
cpu_ms = 100

[[durable_objects.bindings]]
name = "MUTATIONS"
class_name = "MutationsTestStorage"

[[migrations]]
tag = "v1"
new_classes = ["MutationsTestStorage"]
